# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Matthew Lopez-Hays
title: Software Engineer
email: matthewlopezhays@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  itsmyfirstname
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Matt, and im currently a software enginner working for Cigna Healthcare. 
  I am most skilled in: <mark>Python</mark> and <mark>CI/CD</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Conductor
  #       link: propietary 
  #       # link_text: Project Website
  #       # additional_links:
  #       #   - title:  sproogen/modern-resume-theme
  #       #     icon: fab fa-github
  #       #     url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         A common CI/CD pattern for all team applications deploying to company cloud inastructure. 
  #       description: | # this will include new lines to allow paragraphs
  #         This was the first project I was assigned .

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cigna Healthcare
        link: cigna.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: May 2018 - Present
        quote: >
          Cigna is a global health service leader dedicated to helping people improve their health, well-being and sense of security.
        description: | # this will include new lines to allow paragraphs
          Was assigned to the Global Data Retention team.
          Our main responsibility was custodial in nature, as we were tasked with the deletion of data from various source systems. 
          We ingested, classified, sorted, archived, and finally deleted data, following strict rules and protocols provided from our legal team, in compliance with global PII and PHI laws.

          We coordinated with teams in asia, europe, and north america to delete customer data, which posed an undue risk to the company.  

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Quinnipiac University
        caption: 2014 - 2018
        sub_title: BSc Computer Information Systems
        quote: >
          Quinnipiac is a private, coeducational university where students engage in an educational experience that’s both personal and challenging from faculty who care deeply about student outcomes. We offer 150 programs to approximately 7,000 undergraduate and 3,000 graduate students.
        description: | # this will include new lines to allow paragraphs
          Quinnipiac was a sleepy New England university, which fancies itself as a `little ivy`; always raised an eyebrow for me, but i digress.
          My time at Quinnipiac taught me how to work with younger individuals with a greater skill set than myself, and helped me realize how much I enjoy identifying and prefecting patterns.
          Most of my time was spent with my economics professor running through sasticical models, and learning R in the process. Shortly after learning R, I switched my major to CIS, so I 
          could focus on the endless patterns that are associated with technology.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in automaton and software engineering some of my other interests and hobbies are:
      - Flying
      - Carpentry
      - DC Electronics



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
