# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Matthew Lopez-Hays
title: Software Engineer
email: matthewlopezhays@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  itsmyfirstname
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Matt, and im currently a software engineer working for Cigna Healthcare. 
  I am most skilled in: 
    - <mark>Python</mark>
    - <mark>CI/CD</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Conductor
  #       link: propietary 
  #       # link_text: Project Website
  #       # additional_links:
  #       #   - title:  sproogen/modern-resume-theme
  #       #     icon: fab fa-github
  #       #     url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         A common CI/CD pattern for all team applications deploying to company cloud inastructure. 
  #       description: | # this will include new lines to allow paragraphs
  #         This was the first project I was assigned .

  - title: Devops Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CI/CD Pipeline
        # link: cigna.com
        # link_text: boringcompany.com
        sub_title: Software Engineering Advisor
        caption: May 2018 - Present
        quote: >
          A robust pipleline designed to deploy microservices to a kubernetes cluster.
        description: | 
        - test
        - test
        - test


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Quinnipiac University
        caption: 2014 - 2018
        sub_title: BSc Computer Information Systems
        quote: >
          Quinnipiac is a private, coeducational university where students engage in an educational experience that’s both personal and challenging from faculty who care deeply about student outcomes. We offer 150 programs to approximately 7,000 undergraduate and 3,000 graduate students.
        description: | # this will include new lines to allow paragraphs
          My time at Quinnipiac taught me how to work with younger individuals with a greater skill set than myself, and helped me realize how much I enjoy identifying and perfecting patterns.
          Most of my time was spent with my economics professor running through statistic models, and learning R in the process. Shortly after learning R, I switched my major to CIS, so I 
          could focus on the endless patterns that are associated with technology.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in automaton and software engineering some of my other interests and hobbies are:
      - Flying fixed wing and unmanned crafts
      - Carpentry
      - DC Electronics



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
